# Generated by Django 5.2.7 on 2025-10-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('diretor', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Ação', 'Ação'), ('Aventura', 'Aventura'), ('Comédia', 'Comédia'), ('Drama', 'Drama'), ('Terror', 'Terror'), ('Romance', 'Romance'), ('Ficção Científica', 'Ficção Científica'), ('Animação', 'Animação'), ('Documentário', 'Documentário')], max_length=30)),
                ('ano_lancamento', models.PositiveIntegerField()),
                ('sinopse', models.TextField(blank=True, null=True)),
                ('assistido', models.BooleanField(default=False)),
            ],
        ),
    ]
